-- MySQL Script generated by MySQL Workbench
-- Sat Jul 26 12:25:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alquiler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alquiler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alquiler` DEFAULT CHARACTER SET utf8 ;
USE `alquiler` ;

-- -----------------------------------------------------
-- Table `alquiler`.`propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alquiler`.`propietario` (
  `idpropietario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpropietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alquiler`.`inquilino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alquiler`.`inquilino` (
  `idinquilino` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idinquilino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alquiler`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alquiler`.`departamentos` (
  `iddepartamentos` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NOT NULL,
  `precio` INT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL,
  `propietario_idpropietario` INT NOT NULL,
  PRIMARY KEY (`iddepartamentos`),
  INDEX `fk_departamentos_propietario1_idx` (`propietario_idpropietario` ASC) VISIBLE,
  CONSTRAINT `fk_departamentos_propietario1`
    FOREIGN KEY (`propietario_idpropietario`)
    REFERENCES `alquiler`.`propietario` (`idpropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alquiler`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alquiler`.`contrato` (
  `idcontrato` INT NOT NULL AUTO_INCREMENT,
  `duracion` INT NOT NULL,
  `fechadeinicio` DATE NOT NULL,
  `departamentos_iddepartamentos` INT NOT NULL,
  `inquilino_idinquilino` INT NOT NULL,
  PRIMARY KEY (`idcontrato`),
  INDEX `fk_contrato_departamentos1_idx` (`departamentos_iddepartamentos` ASC) VISIBLE,
  INDEX `fk_contrato_inquilino1_idx` (`inquilino_idinquilino` ASC) VISIBLE,
  CONSTRAINT `fk_contrato_departamentos1`
    FOREIGN KEY (`departamentos_iddepartamentos`)
    REFERENCES `alquiler`.`departamentos` (`iddepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_inquilino1`
    FOREIGN KEY (`inquilino_idinquilino`)
    REFERENCES `alquiler`.`inquilino` (`idinquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
